//! Tests derived from the TLA+ formal model.
//!
//! These tests are based on traces generated by the TLA+ model checker
//! in `spec/settlement.tla`. They verify that the runtime invariant checker
//! correctly identifies violations that the formal model would catch.

use crate::settlement::{SettlementStatus, SettlementTracker, check_invariants};

#[test]
fn test_tla_trace_terminal_state_immutability() {
    // This test is derived from a TLA+ trace that would violate
    // terminal state immutability (Settled should never change).
    //
    // Trace from TLA+ model:
    // Queued -> Propagating -> Settled -> Propagating (illegal)

    let mut tracker = SettlementTracker::new();
    let id = [0xAA; 32];

    // Step 1: Queued
    tracker.track(id);

    // Step 2: Queued -> Propagating
    tracker.transition(id, SettlementStatus::Propagating).unwrap();

    // Step 3: Propagating -> Settled
    tracker.transition(id, SettlementStatus::Settled).unwrap();

    // Step 4: Attempt Settled -> Propagating (should be illegal)
    let result = tracker.transition(id, SettlementStatus::Propagating);
    assert!(result.is_err(), "Settled -> Propagating should be illegal");

    // The invariant checker should report that the tracker is healthy
    // since the illegal transition was rejected
    let check_result = check_invariants(&tracker);
    assert!(check_result.is_ok(), "Tracker should be healthy after rejecting illegal transition");
}

#[test]
fn test_tla_trace_disputed_flow() {
    // This test is derived from a TLA+ trace for the Disputed flow.
    //
    // Trace: Queued -> Propagating -> Disputed -> Settled

    let mut tracker = SettlementTracker::new();
    let id = [0xBB; 32];

    tracker.track(id);
    tracker.transition(id, SettlementStatus::Propagating).unwrap();
    tracker.transition(id, SettlementStatus::Disputed).unwrap();
    tracker.transition(id, SettlementStatus::Settled).unwrap();

    // All transitions were legal, so the tracker should be healthy
    let result = check_invariants(&tracker);
    assert!(result.is_ok(), "Disputed -> Settled should be valid");
}

#[test]
fn test_tla_trace_failed_retry() {
    // This test is derived from a TLA+ trace for the Failed retry flow.
    //
    // Trace: Queued -> Propagating -> Failed -> Propagating -> Settled

    let mut tracker = SettlementTracker::new();
    let id = [0xCC; 32];

    tracker.track(id);
    tracker.transition(id, SettlementStatus::Propagating).unwrap();
    tracker.transition(id, SettlementStatus::Failed).unwrap();
    tracker.transition(id, SettlementStatus::Propagating).unwrap();
    tracker.transition(id, SettlementStatus::Settled).unwrap();

    // All transitions were legal, so the tracker should be healthy
    let result = check_invariants(&tracker);
    assert!(result.is_ok(), "Failed -> Propagating -> Settled should be valid");
}

#[test]
fn test_tla_trace_queued_failed_propagating() {
    // This test is derived from a TLA+ trace.
    //
    // Trace: Queued -> Failed -> Propagating -> Disputed -> Failed

    let mut tracker = SettlementTracker::new();
    let id = [0xDD; 32];

    tracker.track(id);
    tracker.transition(id, SettlementStatus::Failed).unwrap();
    tracker.transition(id, SettlementStatus::Propagating).unwrap();
    tracker.transition(id, SettlementStatus::Disputed).unwrap();
    tracker.transition(id, SettlementStatus::Failed).unwrap();

    let result = check_invariants(&tracker);
    assert!(result.is_ok(), "Failed -> Propagating -> Disputed -> Failed should be valid");
}

#[test]
fn test_tla_trace_illegal_settled_transition() {
    // This test uses a mutated tracker to simulate a bug that would
    // be caught by the TLA+ model.
    //
    // The bug: Settled -> Failed (illegal)

    let mut tracker = SettlementTracker::new();
    let id = [0xEE; 32];

    // Bypass the normal API to set a Settled state
    tracker.restore(id, SettlementStatus::Settled);

    // The invariant checker should detect that Settled is a terminal state
    let result = check_invariants(&tracker);
    assert!(result.is_ok(), "Settled alone should pass");

    // Now try to transition from Settled (should be caught by the transition checker)
    let transition_result = tracker.transition(id, SettlementStatus::Failed);
    assert!(transition_result.is_err(), "Settled -> Failed should be illegal");
}
